name: run-elm-test
description: |
  Installs and runs elm-test. It requires the repository to be
  checked out and node and elm to be installed.
runs:
  using: "composite"
  steps:
    - id: install
      run: npm i -g elm-test
      shell: bash
    - id: run
      run: elm-test
      shell: bash

