name: "branch-build"
on: [push]
jobs:
  validate-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ./.github/actions/run-elm-format

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - uses: ./.github/actions/run-elm-test

  build:
    needs: [validate-format, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install elm
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: Build application
        run: elm make ./src/Main.elm --optimize --output elm.js
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: elm-js
          path: ./elm.js

  tag-new-release:
    needs: build
    runs-on: ubuntu-20.04
    outputs:
      version: ${{steps.semanticRelease.outputs.new_release_version}}
    steps:
      - uses: actions/checkout@v3
      - uses: cycjimmy/semantic-release-action@v3
        id: semanticRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: ${{github.ref != 'refs/heads/main'}}
          branches: .*

  build-and-push-container-image:
    needs: tag-new-release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: elm-js
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/ngstmnn/expensemanager-elm:latest
            ghcr.io/ngstmnn/expensemanager-elm:${{needs.tag-new-release.outputs.version}}
