name: "branch-build"
on: [push]
jobs:
  validate-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i -g elm-format
      - run: elm-format ./src --validate

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - uses: ./.github/actions/run-elm-test

  build:
    needs: [validate-format, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - run: elm make ./src/Main.elm --optimize --output elm.js

  tag-new-release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i -g semantic-release@18
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release
