name: "branch-build"
on: [push]
jobs:
  validate-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - run: npm i -g elm-format
      - run: elm-format ./src --validate

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - run: npm i -g elm-test
      - run: elm-test
