name: "branch-build"
on: [push]
jobs:
  validate-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ./.github/actions/run-elm-format

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - uses: ./.github/actions/run-elm-test

  build:
    needs: [validate-format, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install elm
        uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: Build application
        run: elm make ./src/Main.elm --optimize --output elm.js
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: elm-js
          path: ./elm.js

  tag-new-release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i -g semantic-release@18
      - env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release

  build-and-push-container-image:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: elm-json
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
